<template><div class="space-y-6"><div class="flex justify-between items-center"><h2 class="text-2xl font-bold text-glow">缺陷管理</h2><button @click="showForm=true" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm font-semibold hover:shadow-lg hover:shadow-cockpit-accent/25 transition-all">+ 提交缺陷</button></div><div v-if="defects.length" class="space-y-2"><div v-for="d in defects" :key="d.id" class="glass-panel p-4 flex items-center gap-4"><span class="text-xs text-cockpit-muted w-8">#{{d.id}}</span><span class="flex-1 text-sm">{{d.title}}</span><span class="text-xs px-2 py-0.5 rounded" :class="severityBadge(d.severity)">{{severityLabel(d.severity)}}</span><span class="text-xs px-2 py-0.5 rounded" :class="statusBadge(d.status)">{{statusLabel(d.status)}}</span></div></div><p v-else class="text-cockpit-muted py-8 text-center">暂无缺陷</p><div v-if="showForm" class="fixed inset-0 bg-black/60 flex items-center justify-center z-50" @click.self="showForm=false"><div class="glass-panel p-6 w-full max-w-lg"><h3 class="text-lg font-semibold mb-4">提交缺陷</h3><form @submit.prevent="createDefect" class="space-y-3"><input v-model="defectForm.title" placeholder="缺陷标题 *" required class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/><textarea v-model="defectForm.description" placeholder="缺陷描述（复现步骤、预期结果、实际结果）" rows="3" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/><div class="grid grid-cols-2 gap-3"><select v-model="defectForm.severity" class="px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"><option value="minor">轻微</option><option value="major">严重</option><option value="critical">致命</option><option value="trivial">建议</option></select><select v-model="defectForm.priority" class="px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option><option value="low">低</option></select></div><div class="flex justify-end gap-3"><button type="button" @click="showForm=false" class="px-4 py-2 rounded-lg text-sm text-cockpit-muted">取消</button><button type="submit" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm">提交</button></div></form></div></div></div></template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import api from '@/api/client'
const defects = ref<any[]>([])
const showForm = ref(false)
const defectForm = ref({ title:'',description:'',severity:'minor',priority:'medium' })
const statusLabel=(s:string)=>({new:'新建',assigned:'已分配',fixing:'修复中',fixed:'已修复',verified:'已验证',closed:'已关闭',reopened:'重新打开'}[s]||s)
const statusBadge=(s:string)=>({new:'badge-todo',fixed:'badge-done',closed:'badge-done',verified:'badge-done',reopened:'badge-urgent',fixing:'badge-progress'}[s]||'badge-todo')
const severityLabel=(s:string)=>({critical:'致命',major:'严重',minor:'轻微',trivial:'建议'}[s]||s)
const severityBadge=(s:string)=>({critical:'badge-urgent',major:'badge-high',minor:'badge-todo',trivial:'badge-progress'}[s]||'badge-todo')
onMounted(async()=>{try{const r:any=await api.get('/defects');defects.value=r.data?.items||[]}catch{}})
async function createDefect(){try{const r:any=await api.post('/defects',{...defectForm.value,project_id:1,reporter_id:1});if(r.code===200){defects.value.unshift(r.data);showForm.value=false;defectForm.value={title:'',description:'',severity:'minor',priority:'medium'}}}catch{}}
</script>
