<template><div class="space-y-6"><div class="flex justify-between items-center"><h2 class="text-2xl font-bold text-glow">计划管理</h2><button @click="showForm=true" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm font-semibold hover:shadow-lg hover:shadow-cockpit-accent/25 transition-all">+ 创建计划</button></div><div v-if="plans.length" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"><div v-for="p in plans" :key="p.id" class="glass-panel p-4 cursor-pointer hover:scale-[1.01] transition-transform" @click="$router.push(`/plans/${p.id}`)"><div class="flex justify-between items-start mb-2"><h3 class="font-semibold">{{p.name}}</h3><span class="text-xs px-2 py-0.5 rounded" :class="p.status==='active'?'bg-green-500/20 text-green-400':p.status==='draft'?'badge-todo':'badge-done'">{{statusLabel(p.status)}}</span></div><p class="text-xs text-cockpit-muted line-clamp-2">{{p.description||'暂无描述'}}</p><div class="mt-3 flex justify-between text-xs text-cockpit-muted"><span>{{p.start_date?.split('T')[0]}} ~ {{p.end_date?.split('T')[0]}}</span><span :class="priorityColor(p.priority)">{{p.priority==='high'?'高':p.priority==='low'?'低':'中'}}优先级</span></div></div></div><p v-else class="text-cockpit-muted py-8 text-center">暂无计划，点击上方按钮创建</p><div v-if="showForm" class="fixed inset-0 bg-black/60 flex items-center justify-center z-50" @click.self="showForm=false"><div class="glass-panel p-6 w-full max-w-lg mx-4"><h3 class="text-lg font-semibold mb-4">创建计划</h3><form @submit.prevent="createPlan" class="space-y-3"><div><label class="text-xs text-cockpit-muted">计划名称 *</label><input v-model="form.name" required class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/></div><div class="grid grid-cols-2 gap-3"><div><label class="text-xs text-cockpit-muted">开始日期</label><input v-model="form.start_date" type="date" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/></div><div><label class="text-xs text-cockpit-muted">结束日期</label><input v-model="form.end_date" type="date" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/></div></div><div><label class="text-xs text-cockpit-muted">描述</label><textarea v-model="form.description" rows="2" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/></div><div class="flex justify-end gap-3 mt-4"><button type="button" @click="showForm=false" class="px-4 py-2 rounded-lg text-sm text-cockpit-muted hover:text-cockpit-text">取消</button><button type="submit" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm">创建</button></div></form></div></div></div></template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import api from '@/api/client'
const plans = ref<any[]>([])
const showForm = ref(false)
const form = ref({ name:'',description:'',start_date:'',end_date:'' })
const statusLabel=(s:string)=>({draft:'草稿',pending:'待审核',active:'进行中',completed:'已完成'}[s]||s)
const priorityColor=(p:string)=>({high:'text-red-400',medium:'text-yellow-400',low:'text-green-400'}[p]||'')
onMounted(async()=>{try{const r:any=await api.get('/plans');plans.value=r.data?.items||[]}catch{}})
async function createPlan(){
  try{
    const r:any=await api.post('/plans',{...form.value, project_id:1, owner_id:1})
    if(r.code===200){plans.value.unshift(r.data);showForm.value=false;form.value={name:'',description:'',start_date:'',end_date:''}}
  }catch{}
}
</script>
