<template><div class="space-y-6"><button @click="$router.push('/plans')" class="text-sm text-cockpit-gold hover:text-cockpit-accent transition-colors">← 返回计划列表</button><div v-if="plan" class="glass-panel p-5"><h2 class="text-xl font-bold text-glow">{{plan.name}}</h2><p class="text-xs text-cockpit-muted mt-1">{{plan.description}}</p></div><div class="glass-panel p-5"><div class="flex justify-between items-center mb-4"><h3 class="text-sm font-semibold text-cockpit-gold">任务列表 (WBS)</h3><button @click="showTaskForm=true" class="px-3 py-1.5 bg-cockpit-accent/80 rounded text-xs hover:bg-cockpit-accent transition-colors">+ 添加任务</button></div><div v-if="tasks.length" class="space-y-1"><div v-for="t in tasks" :key="t.id" class="flex items-center gap-3 p-2.5 rounded-lg hover:bg-white/5 transition-colors border border-transparent hover:border-cockpit-border/20"><span class="text-xs w-8 text-cockpit-muted">#{{t.id}}</span><span class="flex-1 text-sm">{{t.title}}</span><span class="text-xs px-2 py-0.5 rounded" :class="statusBadge(t.status)">{{statusLabel(t.status)}}</span><span class="text-xs px-2 py-0.5 rounded" :class="priorityBadge(t.priority)">{{t.priority}}</span><select @change="changeStatus(t.id, ($event.target as HTMLSelectElement).value)" class="bg-white/5 border border-cockpit-border/30 rounded text-xs px-2 py-1"><option value="">状态</option><option value="todo">待办</option><option value="in_progress">进行中</option><option value="review">审核中</option><option value="done">完成</option><option value="blocked">阻塞</option></select><button @click="deleteTask(t.id)" class="text-xs text-cockpit-muted hover:text-cockpit-accent">✕</button></div></div><p v-else class="text-cockpit-muted text-sm py-4 text-center">暂无任务</p></div><div v-if="showTaskForm" class="fixed inset-0 bg-black/60 flex items-center justify-center z-50" @click.self="showTaskForm=false"><div class="glass-panel p-6 w-full max-w-md"><h3 class="text-lg font-semibold mb-4">添加任务</h3><form @submit.prevent="createTask" class="space-y-3"><input v-model="taskForm.title" placeholder="任务标题 *" required class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/><textarea v-model="taskForm.description" placeholder="描述" rows="2" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/><div class="flex justify-end gap-3"><button type="button" @click="showTaskForm=false" class="px-4 py-2 rounded-lg text-sm text-cockpit-muted">取消</button><button type="submit" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm">添加</button></div></form></div></div></div></template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import api from '@/api/client'
const route = useRoute()
const plan = ref<any>(null)
const tasks = ref<any[]>([])
const showTaskForm = ref(false)
const taskForm = ref({ title:'',description:'' })
const statusLabel=(s:string)=>({todo:'待办',in_progress:'进行中',review:'审核中',done:'完成',blocked:'阻塞'}[s]||s)
const statusBadge=(s:string)=>({todo:'badge-todo',in_progress:'badge-progress',done:'badge-done',blocked:'badge-blocked',review:'badge-todo'}[s]||'badge-todo')
const priorityBadge=(p:string)=>({urgent:'badge-urgent',high:'badge-high',medium:'badge-todo',low:'badge-progress'}[p]||'')
onMounted(async()=>{try{const id=route.params.id as string;const[pr,tr]:any[]=await Promise.all([api.get('/plans/'+id),api.get('/tasks',{params:{plan_id:id}})]);plan.value=pr.data;tasks.value=tr.data?.items||[]}catch{}})
async function createTask(){try{const id=route.params.id as string;const r:any=await api.post('/tasks',{...taskForm.value,plan_id:+id,project_id:plan.value?.project_id||1});if(r.code===200){tasks.value.push(r.data);showTaskForm.value=false;taskForm.value={title:'',description:''}}}catch{}}
async function changeStatus(taskId:number,status:string){if(!status)return;try{await api.patch('/tasks/'+taskId+'/status',{status});const t=tasks.value.find(x=>x.id===taskId);if(t)t.status=status}catch{}}
async function deleteTask(taskId:number){try{await api.delete('/tasks/'+taskId);tasks.value=tasks.value.filter(x=>x.id!==taskId)}catch{}}
</script>
