<template><div class="space-y-6"><div class="flex justify-between items-center"><h2 class="text-2xl font-bold text-glow">需求池</h2><button @click="showForm=true" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm font-semibold hover:shadow-lg hover:shadow-cockpit-accent/25 transition-all">+ 创建需求</button></div><div v-if="reqs.length" class="space-y-2"><div v-for="r in reqs" :key="r.id" class="glass-panel p-4 flex items-center gap-4"><span class="text-xs text-cockpit-muted w-8">#{{r.id}}</span><span class="flex-1 text-sm">{{r.title}}</span><span class="text-xs px-2 py-0.5 rounded" :class="r.priority==='P0'?'badge-urgent':r.priority==='P1'?'badge-high':'badge-todo'">{{r.priority}}</span><span class="text-xs px-2 py-0.5 rounded" :class="statusBadge(r.status)">{{statusLabel(r.status)}}</span></div></div><p v-else class="text-cockpit-muted py-8 text-center">暂无需求</p><div v-if="showForm" class="fixed inset-0 bg-black/60 flex items-center justify-center z-50" @click.self="showForm=false"><div class="glass-panel p-6 w-full max-w-lg"><h3 class="text-lg font-semibold mb-4">创建需求</h3><form @submit.prevent="createReq" class="space-y-3"><input v-model="reqForm.title" placeholder="需求标题 *" required class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/><textarea v-model="reqForm.description" placeholder="需求描述" rows="2" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"/><select v-model="reqForm.priority" class="w-full px-3 py-2 bg-white/5 border border-cockpit-border/30 rounded-lg text-sm"><option value="P2">P2 - 中</option><option value="P1">P1 - 高</option><option value="P0">P0 - 紧急</option><option value="P3">P3 - 低</option></select><div class="flex justify-end gap-3"><button type="button" @click="showForm=false" class="px-4 py-2 rounded-lg text-sm text-cockpit-muted">取消</button><button type="submit" class="px-4 py-2 bg-cockpit-accent rounded-lg text-sm">创建</button></div></form></div></div></div></template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import api from '@/api/client'
const reqs = ref<any[]>([])
const showForm = ref(false)
const reqForm = ref({ title:'',description:'',priority:'P2' })
const statusLabel=(s:string)=>({draft:'草稿',pending_review:'待评审',approved:'已通过',rejected:'已驳回',in_dev:'开发中',done:'已完成'}[s]||s)
const statusBadge=(s:string)=>({draft:'badge-todo',approved:'badge-done',done:'badge-done',in_dev:'badge-progress',rejected:'badge-blocked'}[s]||'badge-todo')
onMounted(async()=>{try{const r:any=await api.get('/requirements');reqs.value=r.data?.items||[]}catch{}})
async function createReq(){try{const r:any=await api.post('/requirements',{...reqForm.value,project_id:1,proposer_id:1});if(r.code===200){reqs.value.unshift(r.data);showForm.value=false;reqForm.value={title:'',description:'',priority:'P2'}}}catch{}}
</script>
